# Pandas

## 取值

In [30]:
import pandas as pd
df3 = pd.DataFrame([{'學號':'a001','分數':90},{'學號':'a002','分數':85},{'學號':'a003','分數':78}]) #JSON list
df3

分數    學號
0  90  a001
1  85  a002
2  78  a003

In [3]:
df3['分數'] #Series  # =df3.分數

0    90
1    85
2    78
Name: 分數, dtype: int64

In [4]:
df3[['學號','分數']] # # 取得多欄位

學號  分數
0  a001  90
1  a002  85
2  a003  78

In [5]:
df3[1:2] # 取列 

分數    學號
1  85  a002

In [7]:
df3.sort_values(by=['分數'], ascending=True)

分數    學號
2  78  a003
1  85  a002
0  90  a001

In [8]:
df3.sort_values(by=['分數'], ascending=True).reset_index()

index  分數    學號
0      2  78  a003
1      1  85  a002
2      0  90  a001

In [9]:
df3.sort_values(by=['分數'], ascending=True).reset_index(drop=True)

分數    學號
0  78  a003
1  85  a002
2  90  a001

In [10]:
df3['分數']>80

0     True
1     True
2    False
Name: 分數, dtype: bool

In [11]:
df3[df3['分數']>80]  # 根據指定條件取值

分數    學號
0  90  a001
1  85  a002

In [27]:
a=(2,1,6,4,2)
len(a)
help(a.count)

Help on built-in function count:

count(...) method of builtins.tuple instance
    T.count(value) -> integer -- return number of occurrences of value



In [14]:
df3.head(2)  #顯示前 n 列資料 = df3[0:2]

分數    學號
0  90  a001
1  85  a002

In [34]:
df3.tail(2)  #顯示後n列 = df3[-2:]

分數    學號   班級
2  78  a003  四資四
3  95  a004  二技二

In [31]:
df3['班級'] = ['四資四','二技二','四資四']  # 新增欄
df3

分數    學號   班級
0  90  a001  四資四
1  85  a002  二技二
2  78  a003  四資四

In [32]:
# 新增列：append DataFrame（若新增的欄位不存在，會自動新增欄位）
df3 = df3.append(pd.DataFrame([{'分數':95,'學號':'a004','班級':'二技二'}])).reset_index(drop=True)    # append後需要再assign
df3

分數    學號   班級
0  90  a001  四資四
1  85  a002  二技二
2  78  a003  四資四
3  95  a004  二技二

In [35]:
df3 = df3.rename(columns = {'分數':'國文分數'})
df3

國文分數    學號   班級
0    90  a001  四資四
1    85  a002  二技二
2    78  a003  四資四
3    95  a004  二技二

In [36]:
df3.set_index('學號')

國文分數   班級
學號             
a001    90  四資四
a002    85  二技二
a003    78  四資四
a004    95  二技二

In [38]:
df3.loc["a001", "班級"]

'四資四'

In [41]:
df3.loc["a001", "國文分數"] = 100  # 修改資料
df3

國文分數   班級
學號             
a001   100  四資四
a002    85  二技二
a003    78  四資四
a004    95  二技二

In [42]:
del df3['班級']   #刪除欄
df3

國文分數
學號        
a001   100
a002    85
a003    78
a004    95

In [43]:
df3.drop(['a003', 'a001'])  #刪除列

國文分數
學號        
a002    85
a004    95

In [44]:
df4 = pd.DataFrame([{'學號':'a001','分數':90},{'學號':'a002','分數':85},{'學號':'a003','分數':78}])   # JSON list
df4

分數    學號
0  90  a001
1  85  a002
2  78  a003

In [45]:
# 另一種刪除欄位方法 drop 
df4 = df4.drop('分數',axis = 1) # axis=1 表示刪除欄
df4

學號
0  a001
1  a002
2  a003

In [46]:
df4 = df4.drop([0,1]) # 刪除列
df4

學號
2  a003

In [47]:
df5 = pd.DataFrame([{'學號':'a001','分數':90,'班級':'資一乙'},{'學號':'a002','分數':85,'班級':'資二乙'},{'學號':'a003','分數':78,'班級':'資三甲'}])   # JSON list
df5

分數    學號   班級
0  90  a001  資一乙
1  85  a002  資二乙
2  78  a003  資三甲

In [49]:
df5.loc[1,'班級']='資四甲'   # 修改資料
df5

分數    學號   班級
0  90  a001  資一乙
1  85  a002  資四甲
2  78  a003  資三甲

In [51]:
df5.loc[:,'分數']  # :表全部

0    90
1    85
2    78
Name: 分數, dtype: int64

In [52]:
df5.loc[:,'分數']=[100, 90, 80] # 修改指定欄資料
df5

分數    學號   班級
0  100  a001  資一乙
1   90  a002  資四甲
2   80  a003  資三甲

In [53]:
df5.loc[1,:]

分數      90
學號    a002
班級     資四甲
Name: 1, dtype: object

In [54]:
df5.loc[1,:]=[60,'a004','資一乙']
df5

分數    學號   班級
0  100  a001  資一乙
1   60  a004  資一乙
2   80  a003  資三甲

## 移除重複資料

In [55]:
df1 = pd.DataFrame({'name':['John','Mary','Peter','John','Peter','Gene'],'score':[50,80,66,73,83,94]})
df1 

name  score
0   John     50
1   Mary     80
2  Peter     66
3   John     73
4  Peter     83
5   Gene     94

In [56]:
df1.duplicated('name')  # 其中第四筆及第五筆重覆出現, 顯示 True

0    False
1    False
2    False
3     True
4     True
5    False
dtype: bool

In [57]:
df1.drop_duplicates('name')  # 將所選擇的欄位之重覆列刪除, 會留下重覆列的第一個

name  score
0   John     50
1   Mary     80
2  Peter     66
5   Gene     94

In [58]:
df1.drop_duplicates(['name']).reset_index(drop=True) # 重新index

name  score
0   John     50
1   Mary     80
2  Peter     66
3   Gene     94

In [59]:
df1.drop_duplicates(['name'], keep='last') # 挑選重複列的最後一個

name  score
1   Mary     80
3   John     73
4  Peter     83
5   Gene     94

## 排序

In [60]:
df2 = pd.DataFrame({'name':['John','Mary','Peter','John','Peter','Gene'],'scores':[50,80,66,73,83,94]})
df2 

name  scores
0   John      50
1   Mary      80
2  Peter      66
3   John      73
4  Peter      83
5   Gene      94

In [61]:
df2.sort_values(['name','scores'], ascending=[1,0]) # name遞增排列, 分數遞減

name  scores
5   Gene      94
3   John      73
0   John      50
1   Mary      80
4  Peter      83
2  Peter      66

In [62]:
df2 = pd.DataFrame({'姓別':['女','男','男','女','女','男']}) # 資料對應轉換（Mapping）
df2

姓別
0  女
1  男
2  男
3  女
4  女
5  男

In [63]:
sex_to_boolean = {'女':0,'男':1} # 字典(dict)結構
df2['代碼'] = df2['姓別'].map(sex_to_boolean)
df2

姓別  代碼
0  女   0
1  男   1
2  男   1
3  女   0
4  女   0
5  男   1

## 取代

In [64]:
df = pd.DataFrame({'國文':[88,76,'NaN','NaN',90],'英文':[90,'NULL','NULL',66,82],'數學':[67,89,'NaN',71,'NULL']})
df

國文    英文    數學
0   88    90    67
1   76  NULL    89
2  NaN  NULL   NaN
3  NaN    66    71
4   90    82  NULL

In [65]:
df['國文'].replace('NaN',0)

0    88
1    76
2     0
3     0
4    90
Name: 國文, dtype: int64

In [67]:
df.replace(['NaN','NULL'],0)

國文  英文  數學
0  88  90  67
1  76   0  89
2   0   0   0
3   0  66  71
4  90  82   0

In [68]:
df.replace({'NaN':0,'NULL':-1})

國文  英文  數學
0  88  90  67
1  76  -1  89
2   0  -1   0
3   0  66  71
4  90  82  -1

## 遺失值

In [70]:
df = pd.DataFrame({'國文成績':[60,float('NaN'),77,None,78,90,None,78],'英文成績':[71,66,90,58,float('NaN'),90,89,71]})
df 

國文成績  英文成績
0  60.0  71.0
1   NaN  66.0
2  77.0  90.0
3   NaN  58.0
4  78.0   NaN
5  90.0  90.0
6   NaN  89.0
7  78.0  71.0

In [71]:
df = df[df['國文成績'].notnull()]  # 顯示沒有問題的資料, 並指定給df
df

國文成績  英文成績
0  60.0  71.0
2  77.0  90.0
4  78.0   NaN
5  90.0  90.0
7  78.0  71.0

In [75]:
total = df.isnull().sum().sort_values(ascending=False)
print(type(total))
print(total)

<class 'pandas.core.series.Series'>
英文成績    1
國文成績    0
dtype: int64


In [80]:
percent = (df.isnull().sum()/df.isnull().count()).sort_values(ascending=False)
print(type(percent))
print(percent)
print(percent.values)
percent.index

<class 'pandas.core.series.Series'>
英文成績    0.2
國文成績    0.0
dtype: float64
[0.2 0. ]


Index(['英文成績', '國文成績'], dtype='object')

In [77]:
missing_data = pd.concat([total, percent], axis=1, keys=['Total', 'Percent'])  ## series可concat
missing_data

Total  Percent
英文成績      1      0.2
國文成績      0      0.0

In [78]:
missing_data.index

Index(['英文成績', '國文成績'], dtype='object')

In [81]:
import numpy as np
df = pd.DataFrame([[np.nan, np.nan, np.nan, 5], [8, 6, np.nan, np.nan], [4, np.nan, np.nan, 5], 
                   [6, 3, 9, 1],[np.nan, np.nan, np.nan, np.nan]],
                  columns=list('ABCD'))  #columns=['A','B','C','D']←是一個series
df

A    B    C    D
0  NaN  NaN  NaN  5.0
1  8.0  6.0  NaN  NaN
2  4.0  NaN  NaN  5.0
3  6.0  3.0  9.0  1.0
4  NaN  NaN  NaN  NaN

In [88]:
df.dropna() #Remove missing values. 預設how=any

A    B    C    D
3  6.0  3.0  9.0  1.0

In [89]:
df.dropna(how='all') #所有都是na才丟棄

A    B    C    D
0  NaN  NaN  NaN  5.0
1  8.0  6.0  NaN  NaN
2  4.0  NaN  NaN  5.0
3  6.0  3.0  9.0  1.0

In [90]:
df.dropna(axis='index',how='any',subset=['A','D']) #只考慮A,D欄

A    B    C    D
2  4.0  NaN  NaN  5.0
3  6.0  3.0  9.0  1.0

In [93]:
df.dropna(thresh=3) #至少n個值不是nan才顯示=至少n個數值

A    B    C    D
3  6.0  3.0  9.0  1.0

In [94]:
df.describe()  # 統計資料

A        B    C         D
count  3.0  2.00000  1.0  3.000000
mean   6.0  4.50000  9.0  3.666667
std    2.0  2.12132  NaN  2.309401
min    4.0  3.00000  9.0  1.000000
25%    5.0  3.75000  9.0  3.000000
50%    6.0  4.50000  9.0  5.000000
75%    7.0  5.25000  9.0  5.000000
max    8.0  6.00000  9.0  5.000000

In [95]:
df.dtypes

A    float64
B    float64
C    float64
D    float64
dtype: object

In [97]:
df1 = pd.DataFrame({'學號':['a01','a02','a03','a04','a05'],'計概分數':[77,83,56,90,65]})
print(df1)
df2 = pd.DataFrame({'學號':['a01','a02','a04','a06','a07'],'英文分數':[87,90,71,65,97]})
print(df2)

    學號  計概分數
0  a01    77
1  a02    83
2  a03    56
3  a04    90
4  a05    65
    學號  英文分數
0  a01    87
1  a02    90
2  a04    71
3  a06    65
4  a07    97


In [98]:
## =df1.merge(df2, left_on='學號', right_on='學號', how='inner') 
pd.merge(df1,df2, left_on='學號', right_on='學號', how='inner') #  inner join (default) - 取key的交集

學號  計概分數  英文分數
0  a01    77    87
1  a02    83    90
2  a04    90    71

In [99]:
pd.merge(df1,df2, left_on='學號', right_on='學號', how='left') # 左邊為主,沒有的是nan

學號  計概分數  英文分數
0  a01    77  87.0
1  a02    83  90.0
2  a03    56   NaN
3  a04    90  71.0
4  a05    65   NaN

In [100]:
pd.merge(df1,df2, left_on='學號', right_on='學號', how='right') # 以右邊為主

學號  計概分數  英文分數
0  a01  77.0    87
1  a02  83.0    90
2  a04  90.0    71
3  a06   NaN    65
4  a07   NaN    97

In [101]:
pd.merge(df1,df2, left_on='學號', right_on='學號', how='outer') # outer join - 取key聯集

學號  計概分數  英文分數
0  a01  77.0  87.0
1  a02  83.0  90.0
2  a03  56.0   NaN
3  a04  90.0  71.0
4  a05  65.0   NaN
5  a06   NaN  65.0
6  a07   NaN  97.0

# Python 數值運算程式庫- NumPY

In [102]:
import numpy as np 
a = [1,2,3,4]  #list
a = np.array(a) #Numpy array
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3 4]


In [103]:
a.shape # 知道多維陣列的大小，型態是 tuple

(4,)

In [104]:
a= np.array([1,2,3,4,5,6,7,8])
a = a.reshape([2,4])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [105]:
a = np.array([1,2,3,4,5,6])
a[::-1]  # 反轉

array([6, 5, 4, 3, 2, 1])

In [108]:
a = np.arange(24, dtype = 'int32')  
a = a.reshape([3,2,4])
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [109]:
a[0]  # 三維變二維

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [111]:
a[1,:,1:3]    # 1:3表示 1, 2

array([[ 9, 10],
       [13, 14]])

In [112]:
a = np.array([1,2,3,4,5,6])
print ("Numpy Array:" , a)
print ("加:", a + a)
print ("減:" , a - a)
print ("乘:" , a * a)
print ("除:" , a / a)
print ("*0.5" , a * 0.6)

Numpy Array: [1 2 3 4 5 6]
加: [ 2  4  6  8 10 12]
減: [0 0 0 0 0 0]
乘: [ 1  4  9 16 25 36]
除: [1. 1. 1. 1. 1. 1.]
*0.5 [0.6 1.2 1.8 2.4 3.  3.6]


In [117]:
import pandas as pd
df = pd.DataFrame({'ID1':['PM2.5','PM10','CO','PM2.5','PM10','CO','PM2.5','PM10'],
                   'AM8':[8,75,45,31,71,55,90,20],'PM8':[55,73,66,90,99,2,75,60]})
df

ID1  AM8  PM8
0  PM2.5    8   55
1   PM10   75   73
2     CO   45   66
3  PM2.5   31   90
4   PM10   71   99
5     CO   55    2
6  PM2.5   90   75
7   PM10   20   60

In [118]:
df.groupby('ID1').mean()

AM8        PM8
ID1                        
CO     50.000000  34.000000
PM10   55.333333  77.333333
PM2.5  43.000000  73.333333

In [120]:
df.groupby(['ID1'])[['AM8']].mean()  #[['AM8','PM8']]取兩欄

AM8
ID1             
CO     50.000000
PM10   55.333333
PM2.5  43.000000

In [119]:
df.groupby(['ID1']).count()

AM8  PM8
ID1            
CO       2    2
PM10     3    3
PM2.5    3    3

In [121]:
df.groupby(['ID1'])[['PM8']].median()

PM8
ID1       
CO      34
PM10    73
PM2.5   75